### ISSUE TITLE
Have an option to write output to a file. 

### ISSUE THREAD

**Issue by avipatel91** [AdExBlockchain/adex-sample-data#1]
It would be nice if we can provide a command line argument that takes in a file name, should the user want the data to be written to a file.

**Comment by avipatel91** [comment]
I have it implemented here: b43258eb812f4111cd5398c36e3ff2a282daee99

Styling is different but I can PR with your style.

**Comment by Ivshti** [comment]
Please PR, but keep the style consistent :)

**Comment by avipatel91** [comment]
Has been merged: https://github.com/AdExBlockchain/adex-sample-data/commit/6762b8537854a47b288cbf8d4f492c4fee9973f4
